name : AutoSync

on:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'true'
  schedule:
    - cron: '0 0 * * *' # 每天 UTC 时间 00:00 运行
  push:
    branches:
      - master
    paths-ignore:
      - "**/README.md"
env:
  SSH_ACTIONS: false

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:

     - name: Checkout
       uses: actions/checkout@main

     - name: Checkout source repository
       uses: actions/checkout@v2
       with:
          repository: MetaCubeX/meta-rules-dat
          ref: meta
          path: source-repo



  
     - name: Git push assets to "release" branch
       run: |
       
        wget https://github.com/MetaCubeX/mihomo/releases/download/v1.19.9/mihomo-linux-amd64-v1.19.9.gz -O /usr/local/bin/mihomo.gz
        gunzip /usr/local/bin/mihomo.gz
        chmod +x /usr/local/bin/mihomo
        git config --local user.name "github-actions[bot]"
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"

        cd ./target-repo/
        rm -rf *
        git add .
        git commit -m "forDelete"
        git push
        
        cd ..
        cp -r ./source-repo/geo/geosite/cn.list ./target-repo
        cp -r ./source-repo/geo/geosite/geolocation-\!cn.list ./target-repo
        cd ./target-repo/
        sed -i '/browserleak/d' cn.list
        sed -i '/browserleak/d' geolocation-\!cn.list
        sed -i '/ipleak/d' geolocation-\!cn.list
        /usr/local/bin/mihomo convert-ruleset domain text cn.list cn.mrs
        /usr/local/bin/mihomo convert-ruleset domain text  geolocation-\!cn.list  geolocation-\!cn.mrs
        git add .
        git commit -m "new"
        git push

          
     - name: Delete workflow runs
       uses: Mattraks/delete-workflow-runs@main
       with:
        retain_days: 0
        keep_minimum_runs: 6

     - name: Remove old Releases
       uses: dev-drprasad/delete-older-releases@master
       if: env.UPLOAD_RELEASE == 'true' && !cancelled()
       with:
          keep_latest: 6
          delete_tags: true  
       env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

     - name: SSH connection to Actions
       uses: P3TERX/ssh2actions@v1.0.0
       if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
       env:
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
